---
version: "3"
networks:
  app:
services:
  postgresql:
    image: postgres:9.5
    ports:
      - "127.0.0.1::5432"
    environment:
      POSTGRES_PASSWORD: trackerpassword
      POSTGRES_USER: tracker
      POSTGRES_DB: trackerdb
    user: postgres
    networks:
      app:
        aliases:
          - db

  django:
    build:
      context: .
      dockerfile: devops/docker/ProdDjangoDockerfile
      args:
        NPM_VER: 6.13.4
        USERID: 1234
    image: quay.io/freedomofpress/pressfreedomtrackerus
    depends_on:
      - postgresql
    working_dir: /django
    volumes:
      - ${HOST_STATIC_DIR:-fpf-django-media}:/django-media
      - ${HOST_MEDIA_DIR:-fpf-django-static}:/django-static
    environment:
      DJANGO_ALLOWED_HOSTS: app localhost
      DJANGO_COLLECT_STATIC: "yes"
      DJANGO_CREATEDEVDATA: "${DJANGO_CREATEDEVDATA:-no}"
      DJANGO_SETTINGS_MODULE: tracker.settings.production-ci
      # Arbitrary key for this "prod-like" testing setup. Do not use in real life.
      DJANGO_SECRET_KEY: 64a235ef65834d8b42fa2802dd4290cf61c773c3f31332039ec5c48165f744da
      DJANGO_STATIC_ROOT: /django-static
      DJANGO_MEDIA_ROOT: /django-media
      DEPLOY_ENV: prod
      DJANGO_DB_PASSWORD: trackerpassword
      DJANGO_DB_USER: tracker
      DJANGO_DB_NAME: trackerdb
      DJANGO_DB_PORT: 5432
      DJANGO_DB_HOST: db
      DJANGO_XMLTEST_OUTPUT: "yes"
      DJANGO_APP_NAME: tracker
      DJANGO_JSON_LOG: "yes"
      DJANGO_WHITENOISE: "yes"
      # More fake testing keys (see above); generate your own for deployment.
      RECAPTCHA_PUBLIC_KEY: 6LeIxAcTAAAAAJcZVRqyHh71UMIEGNQ_MXjiZKhI
      RECAPTCHA_PRIVATE_KEY: 6LeIxAcTAAAAAGG-vFI1TnRWxMZNFuojJ4WifJWe
    ports:
      - "8000:8000"
    networks:
      app:
        aliases:
          - app

volumes:
  fpf-django-static:
  fpf-django-media:
